stages:
  - build python
  - build python-dev
  - build python-dev-post

include:
  - local:  "python/Build.gitlab-ci.yaml"
  - local:  "python-dev/Build.gitlab-ci.yaml"
  - local:  "ansible/Build.gitlab-ci.yaml"
  - local:  "python-pg-dev/Build.gitlab-ci.yaml"
