image: docker:latest

services:
  - docker:dind

variables:
  IMAGE_BASE: alpine
  ALPINE_VERSION: "3.9"
  PUSH_REGISTERY: registry.gitlab.com/rjango/images

stages:
  # Dep free means it doesn't require any images of ours
  - build-dep-free
  - build-dev
  - build-post-dev

include:
  - local:  "python/.gitlab-ci.yml"
  - local:  "helm/.gitlab-ci.yml"
  - local:  "python-dev/.gitlab-ci.yml"
  - local:  "ansible/.gitlab-ci.yml"
  - local:  "python-pg-dev/.gitlab-ci.yml"
  - local:  "pipenv/.gitlab-ci.yml"
  - local:  "pipenv-dev/.gitlab-ci.yml"
