stages:
  - build
  - build dev
#  - build ansible

include:
  # yamllint disable-line
  - local:  "python/Build.gitlab-ci.yaml"
  - local:  "python-dev/Build.gitlab-ci.yaml"
#  - local:  "ansible/Build.gitlab-ci.yaml"
